### ISSUE TITLE
政治獻金支出登載錯誤

### ISSUE THREAD

**Issue by YauHsien** [g0v/councilor-voter-guide#122]
hlb留言：
剛剛看到 http://councils.g0v.tw/councilors/personal_political_contributions/31a794e87aab4c488bd86e98dd4aa936/2009/#d3_out 這邊有個支出共 2 元 

johnny回應：
hlb: 監察員廉政專刊就寫錯了 P.152 Orz http://sunshine.cy.gov.tw/GipOpenWeb/wSite/public/Attachment/f1278376306279.pdf

**Comment by thewayiam** [comment]
https://github.com/g0v/sunshine.cy/issues/9
