### ISSUE TITLE
請問是否有提供 open API？

### ISSUE THREAD

**Issue by allenlinli** [g0v/councilor-voter-guide#137]
請問是否有提供 open API？
考慮利用 api 做個簡化版的 iOS app。

謝謝

**Comment by thewayiam** [comment]
抱歉太晚回應
http://councils.g0v.tw/api/
api 是直接把資料庫 table 攤開，所以利用起來可能需要一些 join
文件已年久失修，歡迎一起來寫
api 之前有問題，剛修好，還沒做效能調整可能會有一點慢

**Comment by allenlinli** [comment]
謝謝了
