### ISSUE TITLE
花蓮縣工程建議款不知名議員姓名或錯別字

### ISSUE THREAD

**Issue by thewayiam** [g0v/councilor-voter-guide#161]
http://www1.hl.gov.tw/ousv/parliament/index.asp

*2015_01-12
  - 笛布斯是否應為笛布斯顗賚
![image](https://cloud.githubusercontent.com/assets/4479861/24838669/302ad48c-1d7f-11e7-90c2-6e16d0ce9532.png)
![image](https://cloud.githubusercontent.com/assets/4479861/24838668/29285e52-1d7f-11e7-9990-59714e7f995c.png)
![image](https://cloud.githubusercontent.com/assets/4479861/24838672/442545f8-1d7f-11e7-914c-bfe0bef9563e.png)
![image](https://cloud.githubusercontent.com/assets/4479861/24838678/56b0447a-1d7f-11e7-9e1e-a23cfbafc464.png)

*2014_01-12
  - 笛布斯是否應為笛布斯顗賚
![image](https://cloud.githubusercontent.com/assets/4479861/24838686/8dfdbf3e-1d7f-11e7-8a9c-cb536461f27e.png)
![image](https://cloud.githubusercontent.com/assets/4479861/24838690/ad015206-1d7f-11e7-85d1-0701842c7e4c.png)
![image](https://cloud.githubusercontent.com/assets/4479861/24838701/d912c67c-1d7f-11e7-8784-f16dc479c88e.png)
![image](https://cloud.githubusercontent.com/assets/4479861/24838704/eae6b692-1d7f-11e7-83ab-6a9ec30fde43.png)

**Comment by t0mst0ne** [comment]
全名應該是 "笛布斯顗賚"

**Comment by thewayiam** [comment]
是的，大家都寫全名的話不應有例外，周間會回報給縣府，目前都還是先回報給縣市政府請他們確認再修正

**Comment by thewayiam** [comment]
已回報縣長信箱
http://www1.hl.gov.tw/mailbox/mail.asp?p=3
