### ISSUE TITLE
台北市工程建議款的連結點下去，跑到高雄市去

### ISSUE THREAD

**Issue by yurenju** [g0v/councilor-voter-guide#163]
![image](https://cloud.githubusercontent.com/assets/22155/25035986/9eef84b0-2123-11e7-8319-5eebec9e4682.png)
![image](https://cloud.githubusercontent.com/assets/22155/25036009/b4e1d2f0-2123-11e7-8828-162edf84fc50.png)

**Comment by thewayiam** [comment]
應該是在[這行](https://github.com/g0v/councilor-voter-guide/blob/master/voter_guide/suggestions/templates/suggestions/d3/years_bar.html#L133) 覆蓋到前面所有`barGroup`

**Comment by yurenju** [comment]
沒問題了 💯
