### ISSUE TITLE
新竹縣議案提案人空白

### ISSUE THREAD

**Issue by thewayiam** [g0v/councilor-voter-guide#170]
* 2014~2018
  - http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=499
看附件應為（提案人：周江杰）
  - http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=500
看附件應為（提案人：邱靖雅 連署人：周江杰、陳栢維、葉芬英）
  - http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=290
看附件應為（提案人：黃永傳）
  - http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=396
看附件應為（提案人：黃永傳）
  - http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=413
看附件應為（提案人：黃永傳）

**Comment by kiang** [comment]
也許是因為請辭吧
http://news.ltn.com.tw/news/politics/breakingnews/2116729

但沒辦法保留歷史資料也的確是問題

**Comment by thewayiam** [comment]
但高偉凱的都還在XD
名單也還沒更新（http://www.hcc.gov.tw/2016hcc/member/member.php）

**Comment by thewayiam** [comment]
已回報議會官網意見信箱

**Comment by thewayiam** [comment]
對於您來信關心議員提案事宜，提案人無法顯是係因網站系統的問題，目前已經修正下列兩項，另外部分已通知廠商修改中。
 
修正項目如下
(1)建請縣府針對外來植物黑板樹所造成的環境問題進行改善。(提案人:周江杰)
http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=499
 
(2) 為保障學子受教權，建請縣府重新檢討縣三文中預定地之需求。
（提案人：邱靖雅 連署人：周江杰、陳栢維、葉芬英）
http://www.hcc.gov.tw/2016hcc/agenda/porposal-detail.php?porid=92
 
感謝您的來信，並敬祝健康快樂。
 
 
                                          新竹縣議會民意信箱　敬啟
