### ISSUE TITLE
投票指南標題改白色

### ISSUE THREAD

**Issue by shulusama** [g0v/councilor-voter-guide#182]
現在menu上面是黑色的，會被吃掉看不清楚～建議改白色的:D
<img width="855" alt="2017-10-03 12 59 32" src="https://user-images.githubusercontent.com/7334450/31110684-685c212e-a7ce-11e7-80fb-5199b1cc2c65.png">

**Comment by thewayiam** [comment]
發現黑色是我刻意改的😀
改成#eee這樣如何
![image](https://user-images.githubusercontent.com/4479861/31115517-450cb788-a855-11e7-91e2-878140e8dc2b.png)
https://councils.g0v.tw/

**Comment by shulusama** [comment]
棒棒，很清楚:D

**Comment by thewayiam** [comment]
可再看還有沒有什麼要改，沒的話交給你 close 囉
