### ISSUE TITLE
2018 台南的選區有誤

### ISSUE THREAD

**Issue by kiang** [g0v/councilor-voter-guide#183]
https://councils.g0v.tw/candidates/intent_detail/5dfb43a7-5eaf-433f-baff-153d5c09ea5b/

選區應該是 http://k.olc.tw/elections/elections/index/59cfca4e-87cc-415e-af9e-1a2bacb5b862

第01選區[區域]
新營區, 鹽水區, 白河區, 柳營區, 後壁區, 東山區
第02選區[區域]
佳里區, 學甲區, 西港區, 七股區, 將軍區, 北門區
第03選區[區域]
麻豆區, 下營區, 六甲區, 官田區, 大內區
第04選區[區域]
玉井區, 楠西區, 南化區, 左鎮區
第05選區[區域]
新化區, 善化區, 新市區, 安定區, 山上區
第06選區[區域]
安南區
第07選區[區域]
永康區
第08選區[區域]
北區, 中西區
第09選區[區域]
南區, 安平區
第10選區[區域]
東區
第11選區[區域]
仁德區, 歸仁區, 關廟區, 龍崎區
第12選區[平地]
臺南市
第13選區[山地]
臺南市

**Comment by thewayiam** [comment]
從[台南議會官網](http://www.tncc.gov.tw/tnccp/ccp.asp)跟 [wiki](https://zh.wikipedia.org/wiki/%E8%87%BA%E5%8D%97%E5%B8%82%E8%AD%B0%E5%93%A1%E5%88%97%E8%A1%A8) 看來沒錯
你的選區是從哪裡抓的？

**Comment by kiang** [comment]
選區重劃
http://www.cec.gov.tw/tnec/cms/bulletin/26488

**Comment by thewayiam** [comment]
https://github.com/g0v/councilor-voter-guide/issues/152

**Comment by thewayiam** [comment]
你那邊有處理過的選區變更數位檔案或 json 嗎？

**Comment by kiang** [comment]
12 點過了 XD

* https://github.com/kiang/elections/blob/master/Console/Command/data/2018_areas/%E7%9B%B4%E8%BD%84%E5%B8%82%E8%AD%B0%E5%93%A1.json
* https://github.com/kiang/elections/blob/master/Console/Command/data/2018_areas/%E7%B8%A3%E5%B8%82%E8%AD%B0%E5%93%A1.json

**Comment by thewayiam** [comment]
想請教一下選舉區的quota, quota_woman, ivid, code, population, population_electors 的資料來源，感恩

**Comment by kiang** [comment]
目前是沿用去年的資料

* quota, quota_woman 是手動整理的
* ivid, code 來自 https://github.com/g0v/twhgis/ ，我只是把這份資料當作整理行政區的參考基礎，因為原始資料實在太亂
* population, population_electors 是用內政部的人口資料算的 electors = >20 人口數 - http://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=F4478CE5-7A72-4B14-B91A-F4701758328F

**Comment by thewayiam** [comment]
已修正，有空麻煩幫忙review & close，感謝回報問題！

**Comment by kiang** [comment]
試著要更新資料時出現錯誤

"Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later."

然後重新整理頁面、重新送出資料後就 ok 了
