### ISSUE TITLE
新舊選區配對問題

### ISSUE THREAD

**Issue by kiang** [g0v/councilor-voter-guide#185]
台南的選區異動，所以在瀏覽到合併前的選區資料時就無法產生正確的提示

https://councils.g0v.tw/candidates/2014/%E8%87%BA%E5%8D%97%E5%B8%82/11/

**Comment by thewayiam** [comment]
https://github.com/g0v/councilor-voter-guide/commit/96e24235192dc58a2b235a98af2db14535d655ec
加了[對照表](https://github.com/g0v/councilor-voter-guide/blob/master/parser/district_versions.json)，再麻煩幫忙 review & close 了，感謝回報問題

**Comment by kiang** [comment]
可以了，感謝

**Comment by thewayiam** [comment]
留一下紀錄
新的第8選區：北區、中西區，由舊的第11選區、第12選區組成，所以瀏覽舊的11、12兩選區都會連結到新的第8選區
