### ISSUE TITLE
popup 訊息也許可以避免重複出現

### ISSUE THREAD

**Issue by kiang** [g0v/councilor-voter-guide#194]
![screenshot from 2018-01-23 10-57-56](https://user-images.githubusercontent.com/47844/35255932-5ab38902-002c-11e8-91ab-95bfb58ae3bb.png)

也許可以在 cookie 中記錄是否顯示過，現在每次進入畫面都會出現，對於連續性操作會有點困擾

**Comment by thewayiam** [comment]
https://github.com/g0v/councilor-voter-guide/issues/189
應該跟這個重複，我先關掉，有不同需求再開
