### ISSUE TITLE
搜尋建議出現族語，但內頁沒有族語，使搜尋導向到首頁

### ISSUE THREAD

**Issue by audreyt** [g0v/councilor-voter-guide#202]
搜尋欄按 `c` 會出現建議人名：

`車牧勒薩以‧拉勒格安Cemelesailjaljegan`

（註：此處 `Cemelesai` 和 `Ljaljegan` 應分隔）

按下人名會搜尋不到，重新導向到首頁：

https://councils.g0v.tw/?name=%E8%BB%8A%E7%89%A7%E5%8B%92%E8%96%A9%E4%BB%A5%E2%80%A7%E6%8B%89%E5%8B%92%E6%A0%BC%E5%AE%89Cemelesailjaljegan

但只用漢字則可以查得到：

https://councils.g0v.tw/?name=%E8%BB%8A%E7%89%A7%E5%8B%92%E8%96%A9%E4%BB%A5%E2%80%A7%E6%8B%89%E5%8B%92%E6%A0%BC%E5%AE%89

（`伊斯坦大‧貝雅夫‧正福Istanda‧Paingav` 內頁有族語，所以搜尋是正常的。）

**Comment by thewayiam** [comment]
All worded
https://councils.g0v.tw/?name=俄鄧‧殷艾
https://councils.g0v.tw/?name=俄鄧殷艾
https://councils.g0v.tw/?name=Eteng‧Ingay
https://councils.g0v.tw/?name=EtengIngay
https://councils.g0v.tw/?name=俄鄧‧殷艾Eteng‧Ingay
