### ISSUE TITLE
表格顯示排序

### ISSUE THREAD

**Issue by seadog007** [g0v/councilor-voter-guide#93]
一般人第一次看到這個表格沒辦法很快的反應說 是怎麼排序的
上禮拜跟不認識g0v的人介紹的時候被反映的問題
![2014-11-19 11 39 37](https://cloud.githubusercontent.com/assets/5138409/5100403/f9595116-6fe0-11e4-816a-8b151325590d.png)

**Comment by thewayiam** [comment]
已拿掉此頁面
